### ISSUE TITLE
New Student Working on the Project

### ISSUE THREAD

**Issue by BWitemeyer** [tamu-zlp/zlp-scheduler#28]
Hello,

I am one of the students on the team assigned to continue working on this project this semester. Could I get added to the organization? I'm not sure if you'd need any information other than my GitHub username, but let me know if you do.

Thanks!

**Comment by Ceryni** [comment]
Hey @BWitemeyer ,

Could you please e-mail me at `matthew.fitzpatrick@tamu.edu` from your TAMU e-mail with your preferred Github account and Discord Name.

I'll be happy to add you to the org and the discord server we had and then you should have access to everything we had :)
